import { prisma } from "@/lib/db";
import { jsonError, jsonSuccess, requireAuth } from "@/lib/api-utils";
import { validateManifest } from "@marketplace/agent-package-schema";
import { storeExtractedPackage } from "@/lib/package-storage";
import JSZip from "jszip";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  const authResult = await requireAuth();
  if ("error" in authResult) return authResult.error;
  const { userId } = authResult;

  const creator = await prisma.creator.findUnique({
    where: { clerkUserId: userId },
  });
  if (!creator) return jsonError("Creator not found", 404);

  const agent = await prisma.agent.findUnique({
    where: { slug },
    include: {
      versions: { orderBy: { createdAt: "desc" } },
    },
  });

  if (!agent) return jsonError("Agent not found", 404);
  if (agent.creatorId !== creator.id)
    return jsonError("Not authorized", 403);

  return jsonSuccess(agent.versions);
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  const authResult = await requireAuth();
  if ("error" in authResult) return authResult.error;
  const { userId } = authResult;

  const creator = await prisma.creator.findUnique({
    where: { clerkUserId: userId },
  });
  if (!creator) return jsonError("Creator not found", 404);

  const agent = await prisma.agent.findUnique({
    where: { slug },
  });
  if (!agent) return jsonError("Agent not found", 404);
  if (agent.creatorId !== creator.id)
    return jsonError("Not authorized", 403);

  const formData = await request.formData();
  const packageFile = formData.get("package") as File | null;
  const changelog = formData.get("changelog") as string | null;

  if (!packageFile) return jsonError("Package file required", 400);

  // Extract zip
  let zip: JSZip;
  try {
    const buffer = await packageFile.arrayBuffer();
    zip = await JSZip.loadAsync(buffer);
  } catch {
    return jsonError("Invalid zip file", 400);
  }

  // Parse manifest
  const manifestFile = zip.file("marketplace.json");
  if (!manifestFile)
    return jsonError("marketplace.json not found in package", 400);

  let manifest: Record<string, unknown>;
  try {
    const text = await manifestFile.async("string");
    manifest = JSON.parse(text);
  } catch {
    return jsonError("Invalid marketplace.json", 400);
  }

  const errors = validateManifest(manifest);
  if (errors.length > 0) {
    return jsonError(
      `Manifest validation failed: ${errors.map((e) => `${e.field}: ${e.message}`).join("; ")}`,
      400,
    );
  }

  const version = manifest.version as string;
  const versionRuntime = ((manifest.runtime as string) || "openclaw").toUpperCase();

  // Validate custom runtime package contents
  if (versionRuntime === "CUSTOM") {
    if (!zip.file("agent.py")) {
      return jsonError("Custom runtime packages must include agent.py", 400);
    }

    const RESERVED_FILES = [
      "adapter.py",
      "Dockerfile",
      "platform-requirements.txt",
    ];
    for (const reserved of RESERVED_FILES) {
      if (zip.file(reserved)) {
        return jsonError(
          `Package must not contain "${reserved}" — this is a platform-managed file`,
          400,
        );
      }
    }

    const SHADOWED_MODULES = [
      "fastapi.py", "uvicorn.py", "httpx.py", "pydantic.py",
      "json.py", "os.py", "sys.py", "subprocess.py", "socket.py",
      "asyncio.py", "pathlib.py", "importlib.py",
    ];
    for (const mod of SHADOWED_MODULES) {
      if (zip.file(mod)) {
        return jsonError(
          `Package must not contain "${mod}" — this shadows a system module`,
          400,
        );
      }
    }
  }

  // Validate OpenClaw runtime package contents
  if (versionRuntime === "OPENCLAW") {
    if (!zip.file("AGENTS.md")) {
      return jsonError("OpenClaw packages must include AGENTS.md", 400);
    }
    if (!zip.file("SOUL.md")) {
      return jsonError("OpenClaw packages must include SOUL.md", 400);
    }
    const RESERVED_OPENCLAW = ["openclaw.json", ".env"];
    for (const reserved of RESERVED_OPENCLAW) {
      if (zip.file(reserved)) {
        return jsonError(
          `Package must not contain "${reserved}" — this is generated by the platform`,
          400,
        );
      }
    }
  }

  // Enforce minimum pricing per model tier
  const versionModelTier = (manifest.modelTier as string || "").toUpperCase();
  const MIN_PRICE_CENTS: Record<string, number> = {
    HAIKU: 2900,
    SONNET: 9900,
    OPUS: 29900,
  };
  const versionPrice = manifest.pricePerMonth as number | undefined;
  if (versionPrice !== undefined && versionModelTier) {
    const minPrice = MIN_PRICE_CENTS[versionModelTier] || 2900;
    if (versionPrice < minPrice) {
      return jsonError(
        `Minimum price for ${versionModelTier.toLowerCase()} tier is $${(minPrice / 100).toFixed(0)}/month`,
        400,
      );
    }
  }

  // Check version is different from current
  if (version === agent.currentVersion) {
    return jsonError(
      `Version ${version} is the same as current version. Bump the version number.`,
      409,
    );
  }

  // Check version doesn't already exist
  const existingVersion = await prisma.agentVersion.findFirst({
    where: { agentId: agent.id, version },
  });
  if (existingVersion) {
    return jsonError(`Version ${version} already exists`, 409);
  }

  // Store files
  const files = new Map<string, Buffer>();
  for (const [path, entry] of Object.entries(zip.files)) {
    if (!entry.dir) {
      files.set(path, await entry.async("nodebuffer"));
    }
  }
  const storagePath = storeExtractedPackage(slug, version, files);

  // Create version
  const agentVersion = await prisma.agentVersion.create({
    data: {
      agentId: agent.id,
      version,
      packageUrl: `storage://${slug}/${version}`,
      manifestData: manifest as any,
      storagePath,
      changelog: changelog ?? null,
      vetStatus: "PENDING",
    },
  });

  return jsonSuccess(agentVersion, 201);
}
